name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on Ubuntu Linux in GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run preprocessing
        run: python src/preprocess.py

      - name: Run training
        run: python src/train.py

      - name: Run evaluation
        run: python src/evaluate.py

      - name: Run tests
        run: pytest  # Ensure you have tests in place
